import { Input } from "@angular/core";

export class Profissional {
    id: Number;
    @Input() cpf: string;
    @Input() nome: string;
    @Input() nomeMae: string;
    @Input() nomePai: string;
    @Input() dataNascimento: string;
    @Input() sexo: string;
    @Input() idNacionalidade: Number;
    @Input() idNaturalidade: Number;
    @Input() profissionalSus: string;
    @Input() rg: string;
    @Input() dataEmissao: string;
    @Input() orgaoEmissor: string;
    @Input() escolaridade: Number;
    @Input() cep: string;
    @Input() logradouro: string;
    @Input() numero: string;
    @Input() complemento: string;
    @Input() idMunicipio: Number;
    @Input() idUf: Number;
    @Input() bairro: string;
    @Input() foneResidencial: string;
    @Input() foneCelular: Boolean;
    @Input() email: Boolean;
    @Input() idEspecialidade: Number;
    @Input() vinculo: string;
    @Input() crm: string;
    @Input() cargaHorariaSemanal: string;
    @Input() cargoProfissional: string;
    @Input() situacao: Boolean;
    @Input() estabelecimentos : any[];
    @Input() latitude: number;
    @Input() longitude: number;
    @Input() idEstabelecimento : Number = +JSON.parse(localStorage.getItem("est"))[0].id;
    @Input() idTipoUsuario: number;
    @Input() senha : string;
    @Input() confirmaSenha : string;
    @Input() profissionalCNS : Number;
}